- hosts: all
  sudo: yes
  vars:
        zabbix_server_ip: 192.168.215.175
  tasks:
   - name: Get zabbix_agentd config server ip
     shell: cat /etc/zabbix/zabbix_agentd.conf | grep '^Server='
     register: result
     changed_when: false

   - name: debug result var
     debug: var=result

   - name: modify zabbix_agentd config
     replace:
      dest=/etc/zabbix/zabbix_agentd.conf
      regexp=",{{ zabbix_server_ip }}"
      replace=""
     with_items:
      -  zabbix_server_ip

   - name: modify zabbix_agentd config(when writted for leading host)
     replace:
      dest=/etc/zabbix/zabbix_agentd.conf
      regexp="Server={{ zabbix_server_ip }},"
      replace="Server="
     when: result.stdout.find("Server=zabbix_server_ip")
     with_items:
      -  zabbix_server_ip
